name: Revert Main Branch

on:
  workflow_dispatch: # This event triggers the workflow manually

jobs:
  revert_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # This action checks out your repository's code

      - name: Revert Commits
        run: |
          git checkout main
          git revert --no-edit HEAD~17..HEAD # Revert the last 15 commits on the main branch

      - name: Push changes
        run: |
          git push origin main
