name: Manual Git Reset

on:
  workflow_dispatch: # This event triggers the workflow manually

jobs:
  git_reset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # This action checks out your repository's code

      - name: Git Reset
        run: git reset --hard 793fb85 # Reset the code to the last commit

