name: Update DNS Status

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update_dns_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dnspython
        run: pip install dnspython

      - name: Run Python script
        run: python py/rand_dns_chk.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add -f stor/cache.db
          git commit -m "Update DNS status"
          git pull origin main --rebase # Pull changes from the remote repository
          git push

      - name: Check if branch is up to date
        run: |
          git fetch origin
          LOCAL=$(git rev-parse @)
          REMOTE=$(git rev-parse @{u})
          if [ $LOCAL = $REMOTE ]; then
            echo "Branch is up to date."
          else
            echo "Branch is not up to date."
          fi

      - name: Trigger Random Database Cleanup
        if: ${{ !success() || always() }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/workflows/aquarium.yml/dispatches \
            -d '{"ref":"main"}'
