name: Process Phishtank Domains

on:
  workflow_dispatch:

jobs:
  process-domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install dnspython

      - name: Process Phishtank Domains
        run: python py/proc_phishfort.py

      - name: Commit and Push Changes
        run: |
          echo "Committing and pushing changes..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f stor/cache.db
          git commit -m "Update Phishfort to Cache"
          git pull origin main --ff-only  # Pull changes from the remote repository
          git push
          echo "Changes committed and pushed successfully."

      - name: Check if branch is up to date
        run: |
          git fetch origin
          LOCAL=$(git rev-parse @)
          REMOTE=$(git rev-parse @{u})
          if [ $LOCAL = $REMOTE ]; then
            echo "Branch is up to date."
          else
            echo "Branch is not up to date."
          fi

      - name: Trigger Phishnet
        if: ${{ !success() || always() }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/workflows/phishnet.yml/dispatches \
            -d '{"ref":"main"}'
