name: PhishFeed Update

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  update-phishfeed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install sqlite-utils

      - name: Download PhishFeeds
        run: |
          curl -o openphish_feed.txt https://openphish.com/feed.txt
          curl -o phishunt_feed.txt https://phishunt.io/feed.txt

      - name: Combine and Sort PhishFeeds
        run: |
          sort -u openphish_feed.txt phishunt_feed.txt > filtered_feed.txt

      - name: Ensure SQLite Database
        run: |
          sqlite3 cache.db "CREATE TABLE IF NOT EXISTS domains (domain TEXT PRIMARY KEY, last_seen TEXT)"

      - name: Update Database and PhishFeed List
        run: |
          python update.py ${{ github.workspace }}

      - name: Create nxphish.agh
        run: |
          python create_nxphish.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cache.db nxphish.agh
          git commit -m "Update PhishFeed List"
          git push
