name: PhishFeed Update

on:
  workflow_dispatch:

jobs:
  update-phishfeed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install sqlite-utils

      - name: Download PhishFeed from OpenPhish
        run: curl -o openphish_feed.txt https://openphish.com/feed.txt

      - name: Download PhishFeed from Phishunt
        run: curl -o phishunt_feed.txt https://phishunt.io/feed.txt

      - name: Combine and Sort PhishFeeds
        run: |
          cat openphish_feed.txt phishunt_feed.txt | sort -u > filtered_feed.txt

      - name: Run PhishFeed Update
        run: python update.py ${{ github.workspace }}

      - name: Commit and Push Changes
        if: always() && success()  # Always execute, regardless of previous steps and only if the previous step was successful
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add nxphish.agh cache.db
          git commit -m "Update PhishFeed List"
          git push
