name: Watch PhishFeed Update Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-phishfeed-update:
    runs-on: ubuntu-latest

    steps:
      - name: Get PhishFeed Update Workflow runs
        id: get_workflow_runs
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/xRuffKez/NXPhish/actions/workflows/{workflow_id}/runs
          workflow_id: phishnet.yml
          mediaType: '{"previews":["antiope"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger PhishFeed Update Workflow
        if: steps.get_workflow_runs.outputs.data != '[]'  # Trigger nur wenn es vorherige Workflow runs gibt
        run: |
          latest_run_id=$(echo "${{ steps.get_workflow_runs.outputs.data }}" | jq -r '.workflow_runs[0].id')
          echo "Latest run ID: $latest_run_id"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/xRuffKez/NXPhish/actions/runs/$latest_run_id/rerun"
